-- CaptureQuest Postgres runtime schema.
--
-- Source material:
--   - server runtime queries
--   - server/cmd/import-phaser deterministic seed/import code
--   - public/phaser/pokemon.db static source data
--   - server/scripted_events file-backed scripted-event data
--
-- This file is the fresh-database base schema. It intentionally keeps only the
-- tables CaptureQuest currently uses. Imported phaser_* tables avoid foreign
-- keys for now so deterministic static data refreshes cannot cascade into
-- player state.

CREATE TABLE IF NOT EXISTS account (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(254) NOT NULL DEFAULT '',
    password varchar(255) NOT NULL DEFAULT '',
    status integer NOT NULL DEFAULT 0,
    time_creation integer NOT NULL DEFAULT 0,
    discord_id varchar(64) DEFAULT NULL,
    guest_token varchar(64) DEFAULT NULL,
    UNIQUE (name),
    UNIQUE (discord_id),
    UNIQUE (guest_token)
);
CREATE INDEX IF NOT EXISTS account_discord_id_index ON account (discord_id);

CREATE TABLE IF NOT EXISTS account_ip (
    accid integer NOT NULL DEFAULT 0,
    ip varchar(32) NOT NULL DEFAULT '',
    count integer NOT NULL DEFAULT 1,
    lastused timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (accid, ip)
);

CREATE TABLE IF NOT EXISTS variables (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    varname varchar(25) NOT NULL DEFAULT '',
    value text NOT NULL,
    information text NOT NULL,
    ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (varname)
);

CREATE TABLE IF NOT EXISTS character_data (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL DEFAULT 0,
    name varchar(64) NOT NULL DEFAULT '',
    last_name varchar(64) NOT NULL DEFAULT '',
    title varchar(32) NOT NULL DEFAULT '',
    suffix varchar(32) NOT NULL DEFAULT '',
    map_id integer NOT NULL DEFAULT 0,
    y real NOT NULL DEFAULT 0,
    x real NOT NULL DEFAULT 0,
    z real NOT NULL DEFAULT 0,
    heading real NOT NULL DEFAULT 0,
    gender smallint NOT NULL DEFAULT 0,
    faction_id smallint NOT NULL DEFAULT 0,
    class smallint NOT NULL DEFAULT 0,
    birthday integer NOT NULL DEFAULT 0,
    last_login integer NOT NULL DEFAULT 0,
    time_played integer NOT NULL DEFAULT 0,
    gm smallint NOT NULL DEFAULT 0,
    deleted_at timestamp DEFAULT NULL,
    options jsonb DEFAULT NULL,
    UNIQUE (name)
);
CREATE INDEX IF NOT EXISTS character_data_account_id_idx ON character_data (account_id);

CREATE TABLE IF NOT EXISTS character_wallet (
    character_id integer PRIMARY KEY,
    pokedollars integer NOT NULL DEFAULT 0 CHECK (pokedollars >= 0)
);

CREATE TABLE IF NOT EXISTS character_bind (
    id integer NOT NULL,
    slot integer NOT NULL DEFAULT 0,
    map_id integer NOT NULL DEFAULT 0,
    x real NOT NULL DEFAULT 0,
    y real NOT NULL DEFAULT 0,
    z real NOT NULL DEFAULT 0,
    heading real NOT NULL DEFAULT 0,
    PRIMARY KEY (id, slot)
);

CREATE TABLE IF NOT EXISTS character_battle_state (
    character_id integer PRIMARY KEY,
    battle_json text NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS character_coins (
    character_id bigint PRIMARY KEY,
    coins integer NOT NULL DEFAULT 0 CHECK (coins >= 0 AND coins <= 9999)
);

CREATE TABLE IF NOT EXISTS character_collected_hidden_coins (
    character_id bigint NOT NULL,
    hidden_coin_id integer NOT NULL,
    collected_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, hidden_coin_id)
);
CREATE INDEX IF NOT EXISTS character_collected_hidden_coins_hidden_idx ON character_collected_hidden_coins (hidden_coin_id);

CREATE TABLE IF NOT EXISTS character_collected_items (
    character_id integer NOT NULL,
    object_id integer NOT NULL,
    collected_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, object_id)
);

CREATE TABLE IF NOT EXISTS character_defeated_trainers (
    character_id integer NOT NULL,
    trainer_object_id integer NOT NULL,
    defeated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, trainer_object_id)
);

CREATE TABLE IF NOT EXISTS character_event_flags (
    character_id integer NOT NULL,
    flag_name varchar(200) NOT NULL,
    set_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, flag_name)
);

CREATE TABLE IF NOT EXISTS character_in_game_trades (
    character_id integer NOT NULL,
    trade_key varchar(64) NOT NULL,
    given_pokemon_id integer NOT NULL,
    received_pokemon_id integer NOT NULL,
    received_nickname varchar(20) NOT NULL,
    completed_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, trade_key)
);

CREATE TABLE IF NOT EXISTS character_field_move_state (
    character_id bigint NOT NULL,
    move_name varchar(50) NOT NULL,
    map_id integer NOT NULL,
    active smallint NOT NULL DEFAULT 1,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, move_name)
);
CREATE INDEX IF NOT EXISTS character_field_move_state_map_idx ON character_field_move_state (character_id, map_id);

CREATE TABLE IF NOT EXISTS character_object_positions (
    character_id bigint NOT NULL,
    object_id integer NOT NULL,
    map_id integer NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, object_id)
);
CREATE INDEX IF NOT EXISTS character_object_positions_map_idx ON character_object_positions (character_id, map_id);
CREATE INDEX IF NOT EXISTS character_object_positions_coord_idx ON character_object_positions (character_id, map_id, x, y);

CREATE TABLE IF NOT EXISTS character_object_visibility_overrides (
    character_id bigint NOT NULL,
    object_id integer NOT NULL,
    visible boolean NOT NULL,
    source varchar(100) NOT NULL,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (character_id, object_id)
);
CREATE INDEX IF NOT EXISTS character_object_visibility_overrides_object_idx ON character_object_visibility_overrides (object_id);
CREATE INDEX IF NOT EXISTS character_object_visibility_overrides_source_idx ON character_object_visibility_overrides (character_id, source);

CREATE TABLE IF NOT EXISTS character_pc_state (
    character_id integer PRIMARY KEY,
    current_box smallint NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS character_pokedex (
    character_id integer NOT NULL,
    pokemon_id integer NOT NULL,
    seen smallint NOT NULL DEFAULT 0,
    caught smallint NOT NULL DEFAULT 0,
    first_seen_at timestamp DEFAULT NULL,
    first_caught_at timestamp DEFAULT NULL,
    PRIMARY KEY (character_id, pokemon_id)
);

CREATE TABLE IF NOT EXISTS character_pokemon (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id integer NOT NULL,
    party_slot smallint DEFAULT NULL,
    pokemon_id integer NOT NULL,
    nickname varchar(20) DEFAULT '',
    level integer NOT NULL DEFAULT 5,
    exp integer NOT NULL DEFAULT 0,
    growth_rate varchar(20) NOT NULL DEFAULT 'MEDIUM_FAST',
    cur_hp integer NOT NULL,
    max_hp integer NOT NULL,
    iv_atk smallint NOT NULL DEFAULT 0,
    iv_def smallint NOT NULL DEFAULT 0,
    iv_spd smallint NOT NULL DEFAULT 0,
    iv_spc smallint NOT NULL DEFAULT 0,
    ev_hp integer NOT NULL DEFAULT 0,
    ev_atk integer NOT NULL DEFAULT 0,
    ev_def integer NOT NULL DEFAULT 0,
    ev_spd integer NOT NULL DEFAULT 0,
    ev_spc integer NOT NULL DEFAULT 0,
    move1_id integer NOT NULL DEFAULT 0,
    move1_pp smallint NOT NULL DEFAULT 0,
    move1_pp_up smallint NOT NULL DEFAULT 0,
    move2_id integer NOT NULL DEFAULT 0,
    move2_pp smallint NOT NULL DEFAULT 0,
    move2_pp_up smallint NOT NULL DEFAULT 0,
    move3_id integer NOT NULL DEFAULT 0,
    move3_pp smallint NOT NULL DEFAULT 0,
    move3_pp_up smallint NOT NULL DEFAULT 0,
    move4_id integer NOT NULL DEFAULT 0,
    move4_pp smallint NOT NULL DEFAULT 0,
    move4_pp_up smallint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0,
    original_trainer_id integer DEFAULT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
    box smallint NOT NULL DEFAULT -1,
    box_slot smallint NOT NULL DEFAULT -1,
    UNIQUE (character_id, box, box_slot),
    UNIQUE (character_id, party_slot)
);
CREATE INDEX IF NOT EXISTS character_pokemon_character_idx ON character_pokemon (character_id);

CREATE TABLE IF NOT EXISTS character_vermilion_gym_trash_state (
    character_id integer PRIMARY KEY,
    first_lock_can_index smallint NOT NULL CHECK (first_lock_can_index BETWEEN 0 AND 14),
    second_lock_can_index smallint DEFAULT NULL CHECK (second_lock_can_index IS NULL OR second_lock_can_index BETWEEN 0 AND 14),
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS character_daycare (
    character_id integer PRIMARY KEY,
    pokemon_row_id bigint NOT NULL UNIQUE,
    start_level smallint NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS character_daycare_pokemon_idx ON character_daycare (pokemon_row_id);

CREATE TABLE IF NOT EXISTS chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id integer NOT NULL,
    character_name varchar(64) NOT NULL,
    message_type varchar(32) NOT NULL DEFAULT 'say',
    text text NOT NULL,
    map_id integer DEFAULT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS chat_messages_character_idx ON chat_messages (character_id);
CREATE INDEX IF NOT EXISTS chat_messages_created_idx ON chat_messages (created_at);
CREATE INDEX IF NOT EXISTS chat_messages_type_idx ON chat_messages (message_type);

CREATE TABLE IF NOT EXISTS disallowed_words (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word varchar(64) NOT NULL UNIQUE,
    category varchar(32) NOT NULL DEFAULT 'slur',
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS poke_classes (
    id integer PRIMARY KEY,
    name varchar(255) NOT NULL,
    class_type varchar(50) NOT NULL,
    lore text
);

CREATE TABLE IF NOT EXISTS poke_factions (
    id integer PRIMARY KEY,
    name varchar(255) NOT NULL,
    short_name varchar(10) DEFAULT NULL,
    lore text,
    is_playable smallint DEFAULT 1,
    is_starting smallint DEFAULT 1
);

CREATE TABLE IF NOT EXISTS poke_start_cities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id integer NOT NULL,
    name varchar(100) NOT NULL,
    spawn_x integer NOT NULL DEFAULT 0,
    spawn_y integer NOT NULL DEFAULT 0,
    description text,
    sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cq_items (
    id integer PRIMARY KEY,
    name varchar(100) NOT NULL,
    short_name varchar(50) NOT NULL,
    price integer DEFAULT 0,
    vending_price integer DEFAULT NULL,
    item_type smallint DEFAULT 0,
    is_usable boolean DEFAULT false,
    uses_party_menu boolean DEFAULT false,
    is_key_item boolean DEFAULT false,
    is_guard_drink boolean DEFAULT false,
    move_id integer DEFAULT NULL,
    stackable boolean DEFAULT true,
    stack_size integer DEFAULT 99,
    bonus_hp integer DEFAULT 0,
    bonus_attack integer DEFAULT 0,
    bonus_defense integer DEFAULT 0,
    bonus_speed integer DEFAULT 0,
    bonus_special integer DEFAULT 0,
    bonus_accuracy integer DEFAULT 0,
    bonus_evasion integer DEFAULT 0,
    bonus_catch_rate integer DEFAULT 0,
    bonus_exp integer DEFAULT 0,
    bonus_encounter_rate integer DEFAULT 0,
    bonus_crit integer DEFAULT 0,
    bonus_flee integer DEFAULT 0,
    lore_text text,
    icon integer DEFAULT 0,
    heal_amount integer DEFAULT 0,
    status_cure varchar(20) DEFAULT NULL,
    pp_restore integer DEFAULT 0,
    revive_percent integer DEFAULT 0,
    ball_modifier real DEFAULT 0,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cq_item_instances (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id integer NOT NULL,
    mods jsonb DEFAULT NULL,
    charges smallint DEFAULT 0,
    quantity integer DEFAULT 1,
    owner_id integer DEFAULT NULL,
    owner_type smallint DEFAULT 0,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS cq_item_instances_owner_idx ON cq_item_instances (owner_id, owner_type);
CREATE INDEX IF NOT EXISTS cq_item_instances_item_idx ON cq_item_instances (item_id);

CREATE TABLE IF NOT EXISTS cq_character_inventory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id integer NOT NULL,
    item_instance_id integer NOT NULL,
    UNIQUE (character_id, item_instance_id)
);
CREATE INDEX IF NOT EXISTS cq_character_inventory_character_idx ON cq_character_inventory (character_id);
CREATE INDEX IF NOT EXISTS cq_character_inventory_item_instance_idx ON cq_character_inventory (item_instance_id);

CREATE TABLE IF NOT EXISTS cq_merchants (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    map_name varchar(100) DEFAULT NULL,
    map_id integer DEFAULT NULL,
    npc_object_id integer DEFAULT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS cq_merchants_map_id_idx ON cq_merchants (map_id);
CREATE INDEX IF NOT EXISTS cq_merchants_map_name_idx ON cq_merchants (map_name);

CREATE TABLE IF NOT EXISTS cq_merchant_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id integer NOT NULL,
    item_id integer NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    price_override integer DEFAULT NULL,
    quantity integer DEFAULT -1,
    min_level integer DEFAULT 0,
    max_level integer DEFAULT 0,
    UNIQUE (merchant_id, item_id)
);
CREATE INDEX IF NOT EXISTS cq_merchant_items_item_idx ON cq_merchant_items (item_id);

CREATE TABLE IF NOT EXISTS phaser_maps (
    id integer PRIMARY KEY,
    name varchar(100) NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    tileset_id integer DEFAULT NULL,
    is_overworld smallint NOT NULL DEFAULT 0,
    north_connection integer DEFAULT NULL,
    south_connection integer DEFAULT NULL,
    west_connection integer DEFAULT NULL,
    east_connection integer DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS phaser_tile_images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_path varchar(255) NOT NULL,
    tileset_id integer DEFAULT NULL,
    block_index integer DEFAULT NULL,
    position integer DEFAULT NULL,
    raw_foot_tile_id integer DEFAULT NULL,
    talk_over_tile boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS phaser_tiles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x integer NOT NULL,
    y integer NOT NULL,
    tile_image_id integer NOT NULL,
    local_x integer DEFAULT NULL,
    local_y integer DEFAULT NULL,
    map_id integer DEFAULT NULL,
    source_map_id integer DEFAULT NULL,
    collision_type integer DEFAULT 0,
    raw_foot_tile_id integer DEFAULT NULL,
    talk_over_tile boolean NOT NULL DEFAULT false,
    encounter_area_id integer DEFAULT NULL,
    is_user_placed smallint NOT NULL DEFAULT 0,
    placed_by_char_id integer DEFAULT NULL,
    placed_at timestamp DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_tiles_map_idx ON phaser_tiles (map_id);
CREATE INDEX IF NOT EXISTS phaser_tiles_source_map_idx ON phaser_tiles (source_map_id);
CREATE INDEX IF NOT EXISTS phaser_tiles_encounter_area_idx ON phaser_tiles (encounter_area_id);
CREATE INDEX IF NOT EXISTS phaser_tiles_coords_idx ON phaser_tiles (x, y, map_id);
CREATE INDEX IF NOT EXISTS phaser_tiles_overworld_idx ON phaser_tiles (map_id, x, y);
CREATE UNIQUE INDEX IF NOT EXISTS phaser_tiles_coord_unique_idx ON phaser_tiles (x, y, COALESCE(map_id, -1));

CREATE TABLE IF NOT EXISTS phaser_objects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    x integer DEFAULT NULL,
    y integer DEFAULT NULL,
    map_id integer DEFAULT NULL,
    object_type varchar(20) DEFAULT NULL,
    sprite_name varchar(100) DEFAULT NULL,
    name varchar(100) DEFAULT NULL,
    item_id integer DEFAULT NULL,
    action_type varchar(20) DEFAULT NULL,
    action_direction varchar(50) DEFAULT NULL,
    local_x integer DEFAULT NULL,
    local_y integer DEFAULT NULL,
    movement_type varchar(20) DEFAULT 'LAND',
    text varchar(200) DEFAULT NULL,
    trainer_class varchar(50) DEFAULT NULL,
    trainer_party_index integer DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_objects_map_idx ON phaser_objects (map_id);

CREATE TABLE IF NOT EXISTS phaser_warps (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_map_id integer NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    destination_map_id integer DEFAULT NULL,
    destination_map varchar(100) DEFAULT NULL,
    destination_x integer DEFAULT NULL,
    destination_y integer DEFAULT NULL,
    warp_type varchar(10) NOT NULL DEFAULT 'door',
    warp_direction varchar(10) DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_warps_source_map_idx ON phaser_warps (source_map_id);

CREATE TABLE IF NOT EXISTS phaser_items (
    id integer PRIMARY KEY,
    name varchar(100) NOT NULL,
    short_name varchar(50) NOT NULL,
    price integer DEFAULT NULL,
    is_usable smallint DEFAULT 0,
    uses_party_menu smallint DEFAULT 0,
    vending_price integer DEFAULT NULL,
    move_id integer DEFAULT NULL,
    is_guard_drink smallint DEFAULT 0,
    is_key_item smallint DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phaser_pokemon (
    id integer PRIMARY KEY,
    name varchar(50) NOT NULL,
    hp integer NOT NULL,
    atk integer NOT NULL,
    def integer NOT NULL,
    spd integer NOT NULL,
    spc integer NOT NULL,
    type_1 varchar(20) NOT NULL,
    type_2 varchar(20) DEFAULT NULL,
    catch_rate integer NOT NULL,
    base_exp integer NOT NULL,
    growth_rate varchar(20) NOT NULL DEFAULT 'MEDIUM_FAST',
    default_move_1_id varchar(50) DEFAULT NULL,
    default_move_2_id varchar(50) DEFAULT NULL,
    default_move_3_id varchar(50) DEFAULT NULL,
    default_move_4_id varchar(50) DEFAULT NULL,
    base_cry integer DEFAULT NULL,
    cry_pitch integer DEFAULT NULL,
    cry_length integer DEFAULT NULL,
    pokedex_type varchar(50) DEFAULT NULL,
    height varchar(20) DEFAULT NULL,
    weight integer DEFAULT NULL,
    pokedex_text text,
    evolve_level integer DEFAULT NULL,
    evolve_pokemon varchar(50) DEFAULT NULL,
    evolves_from_trade smallint DEFAULT 0,
    icon_image varchar(100) DEFAULT NULL,
    palette_type varchar(50) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS phaser_moves (
    id integer PRIMARY KEY,
    name varchar(50) NOT NULL,
    short_name varchar(50) NOT NULL,
    effect varchar(100) DEFAULT NULL,
    power integer DEFAULT NULL,
    type varchar(20) DEFAULT NULL,
    accuracy integer DEFAULT NULL,
    pp integer DEFAULT NULL,
    battle_animation varchar(100) DEFAULT NULL,
    battle_sound varchar(100) DEFAULT NULL,
    battle_sound_pitch integer DEFAULT NULL,
    battle_sound_tempo integer DEFAULT NULL,
    battle_subanimation varchar(100) DEFAULT NULL,
    battle_tileset integer DEFAULT NULL,
    battle_delay integer DEFAULT NULL,
    is_hm smallint DEFAULT 0,
    field_move_effect integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phaser_dialogue_text (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label varchar(200) NOT NULL UNIQUE,
    source_file varchar(200) NOT NULL,
    dialogue text NOT NULL
);

CREATE TABLE IF NOT EXISTS phaser_text_pointers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    text_constant varchar(200) NOT NULL,
    local_label varchar(200) NOT NULL,
    dialogue_label varchar(200) DEFAULT NULL,
    pointer_index integer DEFAULT 0,
    is_trainer smallint DEFAULT 0
);
CREATE INDEX IF NOT EXISTS phaser_text_pointers_constant_idx ON phaser_text_pointers (text_constant);
CREATE INDEX IF NOT EXISTS phaser_text_pointers_map_idx ON phaser_text_pointers (map_name);

CREATE TABLE IF NOT EXISTS phaser_trainer_headers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    header_label varchar(200) NOT NULL,
    header_index integer NOT NULL,
    event_flag varchar(200) DEFAULT NULL,
    sight_range integer DEFAULT NULL,
    battle_text_label varchar(200) DEFAULT NULL,
    end_battle_text_label varchar(200) DEFAULT NULL,
    after_battle_text_label varchar(200) DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_trainer_headers_map_name_idx ON phaser_trainer_headers (map_name);
CREATE INDEX IF NOT EXISTS phaser_trainer_headers_map_id_idx ON phaser_trainer_headers (map_id);

CREATE TABLE IF NOT EXISTS phaser_pokemon_learnset (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id integer NOT NULL,
    pokemon_name varchar(50) NOT NULL,
    level integer NOT NULL,
    move_name varchar(50) NOT NULL,
    move_id integer DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_pokemon_learnset_pokemon_idx ON phaser_pokemon_learnset (pokemon_id);
CREATE INDEX IF NOT EXISTS phaser_pokemon_learnset_level_idx ON phaser_pokemon_learnset (pokemon_id, level);

CREATE TABLE IF NOT EXISTS phaser_pokemon_tmhm (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id integer NOT NULL,
    pokemon_name varchar(50) NOT NULL,
    tm_hm_name varchar(10) NOT NULL,
    move_name varchar(50) NOT NULL,
    move_id integer DEFAULT NULL,
    is_hm smallint DEFAULT 0
);
CREATE INDEX IF NOT EXISTS phaser_pokemon_tmhm_pokemon_idx ON phaser_pokemon_tmhm (pokemon_id);
CREATE INDEX IF NOT EXISTS phaser_pokemon_tmhm_name_idx ON phaser_pokemon_tmhm (pokemon_id, tm_hm_name);

CREATE TABLE IF NOT EXISTS phaser_wild_encounters (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    encounter_type varchar(20) NOT NULL,
    encounter_rate integer NOT NULL DEFAULT 0,
    slot_index integer NOT NULL,
    pokemon_name varchar(50) NOT NULL,
    level integer NOT NULL,
    version varchar(10) DEFAULT 'both'
);
CREATE INDEX IF NOT EXISTS phaser_wild_encounters_map_id_idx ON phaser_wild_encounters (map_id);
CREATE INDEX IF NOT EXISTS phaser_wild_encounters_map_name_idx ON phaser_wild_encounters (map_name);

CREATE TABLE IF NOT EXISTS phaser_encounter_slots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_index integer NOT NULL,
    probability double precision NOT NULL,
    cumulative_probability double precision NOT NULL
);

CREATE TABLE IF NOT EXISTS phaser_trainer_classes (
    id integer PRIMARY KEY,
    constant_name varchar(50) NOT NULL UNIQUE,
    display_name varchar(50) NOT NULL,
    base_money integer NOT NULL DEFAULT 0,
    is_gym_leader smallint DEFAULT 0,
    is_elite_four smallint DEFAULT 0,
    is_rival smallint DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phaser_trainer_parties (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_class_id integer NOT NULL,
    party_index integer NOT NULL,
    location_comment varchar(200) DEFAULT NULL,
    is_variable_level smallint DEFAULT 0
);
CREATE INDEX IF NOT EXISTS phaser_trainer_parties_class_idx ON phaser_trainer_parties (trainer_class_id);

CREATE TABLE IF NOT EXISTS phaser_trainer_party_pokemon (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_party_id integer NOT NULL,
    slot_index integer NOT NULL,
    pokemon_name varchar(50) NOT NULL,
    level integer NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_trainer_party_pokemon_party_idx ON phaser_trainer_party_pokemon (trainer_party_id);

CREATE TABLE IF NOT EXISTS phaser_hidden_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_constant varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    x integer NOT NULL,
    y integer NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_hidden_items_map_idx ON phaser_hidden_items (map_id);

CREATE TABLE IF NOT EXISTS phaser_hidden_coins (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_constant varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    coin_amount integer NOT NULL DEFAULT 10
);
CREATE INDEX IF NOT EXISTS phaser_hidden_coins_map_idx ON phaser_hidden_coins (map_id);

CREATE TABLE IF NOT EXISTS phaser_hidden_objects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_constant varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    item_or_direction varchar(200) DEFAULT NULL,
    routine varchar(200) DEFAULT NULL,
    object_type varchar(50) DEFAULT 'hidden',
    item_id integer DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_hidden_objects_map_idx ON phaser_hidden_objects (map_id);

CREATE TABLE IF NOT EXISTS phaser_missable_objects (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hs_index integer NOT NULL,
    hs_constant varchar(100) NOT NULL UNIQUE,
    map_constant varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    object_constant varchar(100) NOT NULL,
    object_index integer DEFAULT NULL,
    object_name varchar(100) DEFAULT NULL,
    object_type varchar(20) DEFAULT NULL,
    initial_state varchar(10) NOT NULL,
    initial_visible smallint NOT NULL,
    label varchar(255) NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_missable_objects_map_idx ON phaser_missable_objects (map_id);
CREATE INDEX IF NOT EXISTS phaser_missable_objects_object_name_idx ON phaser_missable_objects (object_name);

CREATE TABLE IF NOT EXISTS phaser_event_object_visibility (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id integer NOT NULL,
    map_name varchar(100) NOT NULL,
    object_name varchar(100) NOT NULL,
    visible boolean NOT NULL,
    requires_flag varchar(100) DEFAULT NULL,
    requires_flag_absent varchar(100) DEFAULT NULL,
    label varchar(255) DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_event_object_visibility_map_idx ON phaser_event_object_visibility (map_id);
CREATE INDEX IF NOT EXISTS phaser_event_object_visibility_object_idx ON phaser_event_object_visibility (map_id, object_name);
CREATE INDEX IF NOT EXISTS phaser_event_object_visibility_flags_idx ON phaser_event_object_visibility (requires_flag, requires_flag_absent);

CREATE TABLE IF NOT EXISTS phaser_map_music (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_constant varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    music_constant varchar(100) NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_map_music_map_id_idx ON phaser_map_music (map_id);
CREATE INDEX IF NOT EXISTS phaser_map_music_map_constant_idx ON phaser_map_music (map_constant);

CREATE TABLE IF NOT EXISTS phaser_map_scripts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    script_index integer NOT NULL,
    script_label varchar(200) NOT NULL,
    script_constant varchar(200) NOT NULL,
    raw_asm text,
    map_id integer DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_map_scripts_map_name_idx ON phaser_map_scripts (map_name);
CREATE INDEX IF NOT EXISTS phaser_map_scripts_map_id_idx ON phaser_map_scripts (map_id);

CREATE TABLE IF NOT EXISTS phaser_npc_movement_data (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    label varchar(200) NOT NULL,
    movements text NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_npc_movement_data_map_name_idx ON phaser_npc_movement_data (map_name);

CREATE TABLE IF NOT EXISTS phaser_event_flags (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    flag_name varchar(200) NOT NULL,
    operation varchar(20) NOT NULL,
    context_label varchar(200) DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_event_flags_map_name_idx ON phaser_event_flags (map_name);
CREATE INDEX IF NOT EXISTS phaser_event_flags_flag_name_idx ON phaser_event_flags (flag_name);

CREATE TABLE IF NOT EXISTS phaser_in_game_trades (
    trade_key varchar(64) PRIMARY KEY,
    text_constant varchar(255) NOT NULL UNIQUE,
    map_name varchar(100) NOT NULL,
    source_file varchar(255) NOT NULL,
    script_label varchar(255) NOT NULL,
    requested_pokemon_id integer NOT NULL,
    requested_pokemon_name varchar(50) NOT NULL,
    offered_pokemon_id integer NOT NULL,
    offered_pokemon_name varchar(50) NOT NULL,
    offered_nickname varchar(20) NOT NULL,
    dialogue_set varchar(20) NOT NULL CHECK (dialogue_set IN ('CASUAL', 'EVOLUTION', 'HAPPY')),
    original_trade_index integer DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_in_game_trades_text_idx ON phaser_in_game_trades (text_constant);
CREATE INDEX IF NOT EXISTS phaser_in_game_trades_map_idx ON phaser_in_game_trades (map_name);

CREATE TABLE IF NOT EXISTS phaser_boulder_targets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_family varchar(50) NOT NULL,
    map_name varchar(100) NOT NULL,
    source_label varchar(100) NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    flag varchar(100) NOT NULL,
    drops_through_hole boolean NOT NULL DEFAULT false,
    source_missable_object varchar(100) NOT NULL DEFAULT '',
    source_object_name varchar(100) NOT NULL DEFAULT '',
    destination_map_name varchar(100) NOT NULL DEFAULT '',
    destination_missable_object varchar(100) NOT NULL DEFAULT '',
    destination_object_name varchar(100) NOT NULL DEFAULT '',
    source_file varchar(255) NOT NULL DEFAULT '',
    UNIQUE (target_family, map_name, x, y)
);
CREATE INDEX IF NOT EXISTS phaser_boulder_targets_family_map_idx ON phaser_boulder_targets (target_family, map_name);
CREATE INDEX IF NOT EXISTS phaser_boulder_targets_flag_idx ON phaser_boulder_targets (flag);

CREATE TABLE IF NOT EXISTS phaser_coordinate_triggers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    label varchar(200) NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    map_id integer DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_coordinate_triggers_map_name_idx ON phaser_coordinate_triggers (map_name);
CREATE INDEX IF NOT EXISTS phaser_coordinate_triggers_map_id_idx ON phaser_coordinate_triggers (map_id);

CREATE TABLE IF NOT EXISTS phaser_warp_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    map_id integer DEFAULT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    dest_map varchar(100) NOT NULL,
    dest_warp_index integer NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_warp_events_map_id_idx ON phaser_warp_events (map_id);
CREATE INDEX IF NOT EXISTS phaser_warp_events_map_name_idx ON phaser_warp_events (map_name);

CREATE TABLE IF NOT EXISTS phaser_cutscene_scripts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_label varchar(255) NOT NULL UNIQUE,
    map_name varchar(100) NOT NULL,
    trigger_type varchar(20) NOT NULL DEFAULT 'map_script' CHECK (trigger_type IN ('coord', 'map_script', 'npc_click')),
    trigger_label varchar(255) DEFAULT NULL,
    requires_flag varchar(100) DEFAULT NULL,
    requires_flag_absent varchar(100) DEFAULT NULL,
    requires_flags jsonb DEFAULT NULL,
    requires_flags_absent jsonb DEFAULT NULL,
    requires_item_id integer DEFAULT NULL,
    requires_item_absent_id integer DEFAULT NULL,
    requires_pokedex_caught integer DEFAULT NULL,
    requires_money integer DEFAULT NULL,
    requires_money_below integer DEFAULT NULL,
    requires_coins integer DEFAULT NULL,
    requires_coins_below integer DEFAULT NULL,
    requires_player_facing varchar(10) DEFAULT NULL,
    sets_flags jsonb DEFAULT NULL,
    actions jsonb NOT NULL,
    warp_to_map_id integer DEFAULT NULL,
    warp_to_x integer DEFAULT NULL,
    warp_to_y integer DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS phaser_cutscene_scripts_trigger_label_idx ON phaser_cutscene_scripts (trigger_label);
CREATE INDEX IF NOT EXISTS phaser_cutscene_scripts_requires_item_idx ON phaser_cutscene_scripts (requires_item_id);
CREATE INDEX IF NOT EXISTS phaser_cutscene_scripts_requires_absent_item_idx ON phaser_cutscene_scripts (requires_item_absent_id);
CREATE INDEX IF NOT EXISTS phaser_cutscene_scripts_requires_caught_idx ON phaser_cutscene_scripts (requires_pokedex_caught);
CREATE INDEX IF NOT EXISTS phaser_cutscene_scripts_requires_money_idx ON phaser_cutscene_scripts (requires_money, requires_money_below);
CREATE INDEX IF NOT EXISTS phaser_cutscene_scripts_requires_coins_idx ON phaser_cutscene_scripts (requires_coins, requires_coins_below);

CREATE TABLE IF NOT EXISTS phaser_event_tile_overrides (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id integer NOT NULL,
    map_name varchar(100) NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    tile_image_id integer NOT NULL,
    collision_type integer NOT NULL DEFAULT 0,
    requires_flag varchar(100) DEFAULT NULL,
    requires_flag_absent varchar(100) DEFAULT NULL,
    label varchar(255) DEFAULT NULL,
    UNIQUE (map_id, x, y, requires_flag, requires_flag_absent)
);
CREATE INDEX IF NOT EXISTS phaser_event_tile_overrides_map_idx ON phaser_event_tile_overrides (map_id);
CREATE INDEX IF NOT EXISTS phaser_event_tile_overrides_flags_idx ON phaser_event_tile_overrides (requires_flag, requires_flag_absent);

CREATE TABLE IF NOT EXISTS phaser_game_corner_prizes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prize_type varchar(20) NOT NULL CHECK (prize_type IN ('pokemon', 'tm')),
    pokemon_id integer DEFAULT NULL,
    tm_move_id integer DEFAULT NULL,
    item_id integer DEFAULT NULL,
    prize_name varchar(50) NOT NULL,
    coin_cost integer NOT NULL,
    sort_order integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS phaser_elevator_floors (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    elevator_map_id integer NOT NULL,
    floor_map_id integer NOT NULL,
    floor_label varchar(16) NOT NULL,
    dest_x integer NOT NULL,
    dest_y integer NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    requires_flag varchar(64) DEFAULT NULL,
    requires_item_id integer DEFAULT NULL,
    UNIQUE (elevator_map_id, floor_map_id)
);
CREATE INDEX IF NOT EXISTS phaser_elevator_floors_requires_item_idx ON phaser_elevator_floors (requires_item_id);

CREATE TABLE IF NOT EXISTS phaser_warp_tiles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_map_id integer NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    destination_map_id integer NOT NULL,
    destination_x integer NOT NULL,
    destination_y integer NOT NULL,
    UNIQUE (source_map_id, x, y)
);

CREATE TABLE IF NOT EXISTS phaser_encounter_areas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    encounter_rate integer NOT NULL DEFAULT 0,
    encounter_type varchar(20) NOT NULL DEFAULT 'grass'
);

CREATE TABLE IF NOT EXISTS phaser_encounter_area_slots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_area_id integer NOT NULL,
    slot_index integer NOT NULL,
    pokemon_id integer NOT NULL,
    level integer NOT NULL,
    probability real NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_encounter_area_slots_area_idx ON phaser_encounter_area_slots (encounter_area_id);
CREATE INDEX IF NOT EXISTS phaser_encounter_area_slots_pokemon_idx ON phaser_encounter_area_slots (pokemon_id);

CREATE TABLE IF NOT EXISTS phaser_tile_properties (
    tile_image_id integer PRIMARY KEY,
    name varchar(100) DEFAULT '',
    collision_type integer NOT NULL DEFAULT 0,
    is_user_editable boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS phaser_tile_animations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tile_image_id integer NOT NULL,
    frame_index integer NOT NULL DEFAULT 0,
    frame_image_path varchar(255) NOT NULL,
    frame_duration_ms integer NOT NULL DEFAULT 500,
    UNIQUE (tile_image_id, frame_index)
);

CREATE TABLE IF NOT EXISTS phaser_spin_tiles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    movements jsonb NOT NULL,
    UNIQUE (map_name, x, y)
);

CREATE TABLE IF NOT EXISTS phaser_stamps (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    width_tiles integer NOT NULL,
    height_tiles integer NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS phaser_stamp_tiles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stamp_id integer NOT NULL,
    offset_x integer NOT NULL,
    offset_y integer NOT NULL,
    tile_image_id integer NOT NULL
);
CREATE INDEX IF NOT EXISTS phaser_stamp_tiles_stamp_idx ON phaser_stamp_tiles (stamp_id);

CREATE TABLE IF NOT EXISTS phaser_branching_dialogue (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_name varchar(100) DEFAULT NULL,
    prompt_text_constant varchar(255) NOT NULL UNIQUE,
    prompt_text varchar(512) NOT NULL,
    yes_text_constant varchar(255) DEFAULT NULL,
    no_text_constant varchar(255) DEFAULT NULL,
    yes_dialogue text,
    no_dialogue text,
    requires_event_flag varchar(100) DEFAULT NULL,
    sets_event_flag varchar(100) DEFAULT NULL,
    yes_actions jsonb DEFAULT NULL,
    no_actions jsonb DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS phaser_conditional_dialogue (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text_constant varchar(255) NOT NULL,
    priority integer NOT NULL DEFAULT 0,
    requires_flag varchar(100) DEFAULT NULL,
    requires_flag_absent varchar(100) DEFAULT NULL,
    requires_flags jsonb DEFAULT NULL,
    requires_flags_absent jsonb DEFAULT NULL,
    override_dialogue text NOT NULL,
    override_speaker varchar(100) DEFAULT NULL,
    dialogue_labels jsonb DEFAULT NULL,
    source varchar(100) DEFAULT 'manual'
);
CREATE INDEX IF NOT EXISTS phaser_conditional_dialogue_text_idx ON phaser_conditional_dialogue (text_constant);
CREATE INDEX IF NOT EXISTS phaser_conditional_dialogue_priority_idx ON phaser_conditional_dialogue (text_constant, priority DESC);
