#!/usr/bin/env python3
"""Copy generated extractor outputs into CaptureQuest runtime asset folders."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sqlite3
import time
import urllib.error
import urllib.request
import warnings
from pathlib import Path

from PIL import Image

warnings.filterwarnings("ignore", category=DeprecationWarning)


CAPTUREQUEST_ONLY_PHASER_SPRITES = {
    "bluenb.png",
    "cavern_sign.png",
    "forest_sign.png",
    "red_surf.png",
    "red_surf_original.png",
    "sign.png",
}

# Stable art identities used by the optional procedural overworld preview.
# Globally deduplicated tile IDs can move, but these decoded source-art hashes
# remain stable across extractor schema changes.
PROCEDURAL_TILE_HASHES = {
    "1": {"0": "6b7e876b7db1eb10202bd929f02d0e83", "1": "025437b14e57a6656eaf1ef23b29a6a1"},
    "4": {"0": "797ab87f76a724788ddbed907d8e8f37"},
    "6": {"0": "a945eb658112a4a701fd54923bf2a304", "3": "7914fd4b5ab37ac6ba7f455354d7ba81"},
    "11": {"0": "05c950f739d7130d4e6359eaa2c7d593"},
    "29": {"0": "164733daf72c7a0dc5c6c59ddc352641", "1": "52af236c78e5becb8bcedea202419645", "2": "424423c06a1cca8181d0e19d12915515"},
    "30": {"1": "f779949ec8e7a8eb1fa2df179fa57ca0", "3": "021ce51ac62ef9cf308dafedf72c02cf"},
    "36": {"0": "e9d6654922f4228a106e6b2ffe88d89b", "2": "9c24ea23c85eb2098fe4daa4e0743b63"},
    "37": {"1": "aaab0c6724a83a5cd8d939eba398a317", "3": "dc542cbf5040dc1b8644c46851b05804"},
    "59": {"0": "b79e3caf967bd96cd0181953af7dd009", "1": "c5622b12de36880b7688377e8c2a1c4f"},
    "62": {"0": "6c567c31bfd3dea400ff83a3ad843005"},
}


def clean_dir(path: Path, keep_names: set[str] | None = None) -> None:
    keep_names = keep_names or set()
    path.mkdir(parents=True, exist_ok=True)
    for child in path.iterdir():
        if child.name in keep_names:
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def copy_file(source: Path, destination: Path) -> None:
    if not source.exists():
        raise FileNotFoundError(source)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def copy_tree_contents(source: Path, destination: Path) -> int:
    if not source.exists():
        raise FileNotFoundError(source)
    count = 0
    for source_file in sorted(source.rglob("*")):
        if not source_file.is_file():
            continue
        relative = source_file.relative_to(source)
        copy_file(source_file, destination / relative)
        count += 1
    return count


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def tile_catalog_sha256(tile_directory: Path) -> tuple[int, str]:
    digest = hashlib.sha256()
    files = sorted(tile_directory.glob("tile_*.png"))
    for tile_file in files:
        digest.update(tile_file.name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(bytes.fromhex(sha256_file(tile_file)))
    return len(files), digest.hexdigest()


def write_runtime_asset_contract(phaser_root: Path, database: Path) -> str:
    with sqlite3.connect(database) as conn:
        expected_tiles = conn.execute("SELECT COUNT(*) FROM tile_images").fetchone()[0]
        min_id, max_id = conn.execute(
            "SELECT MIN(id), MAX(id) FROM tile_images"
        ).fetchone()
        schema_row = conn.execute(
            "SELECT schema_name, schema_version, minimum_reader_version FROM schema_metadata LIMIT 1"
        ).fetchone()

    tile_count, tile_digest = tile_catalog_sha256(phaser_root / "tile_images")
    if tile_count != expected_tiles or min_id != 1 or max_id != expected_tiles:
        raise RuntimeError(
            "Runtime tile assets do not form the exact 1-indexed database catalog: "
            f"files={tile_count}, rows={expected_tiles}, ids={min_id}..{max_id}"
        )

    contract = {
        "schemaName": schema_row[0],
        "schemaVersion": schema_row[1],
        "minimumReaderVersion": schema_row[2],
        "pokemonDbSha256": sha256_file(database),
        "tileCount": tile_count,
        "tileCatalogSha256": tile_digest,
    }
    contract_path = phaser_root / "runtime_asset_contract.json"
    contract_path.write_text(
        json.dumps(contract, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return tile_digest


def write_runtime_asset_version(repo_root: Path, tile_catalog_sha256: str) -> None:
    version_path = repo_root / "src/constants/runtime_asset_version.ts"
    version_path.write_text(
        "// Generated by scripts/sync_extractor_assets.py. Do not edit by hand.\n"
        "export const RUNTIME_TILE_ASSET_VERSION =\n"
        f'  "{tile_catalog_sha256}";\n',
        encoding="utf-8",
    )


def write_procedural_tile_palette(repo_root: Path, database: Path) -> None:
    with sqlite3.connect(database) as conn:
        image_ids = {
            image_hash: image_id
            for image_id, image_hash in conn.execute(
                "SELECT id, image_hash FROM tile_images"
            )
        }

    palette: dict[str, dict[str, int]] = {}
    for block_index, positions in PROCEDURAL_TILE_HASHES.items():
        palette[block_index] = {}
        for position, image_hash in positions.items():
            image_id = image_ids.get(image_hash)
            if image_id is None:
                raise RuntimeError(
                    "Procedural terrain artwork is missing from the extractor "
                    f"catalog: block={block_index}, position={position}, hash={image_hash}"
                )
            palette[block_index][position] = image_id

    palette_path = repo_root / "src/constants/procedural_tile_palette.json"
    palette_path.write_text(
        json.dumps(palette, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def make_color_transparent(path: Path, color: tuple[int, int, int]) -> None:
    image = Image.open(path).convert("RGBA")
    pixels = []
    for red, green, blue, alpha in image.getdata():
        if (red, green, blue) == color:
            pixels.append((red, green, blue, 0))
        else:
            pixels.append((red, green, blue, alpha))
    image.putdata(pixels)
    image.save(path)


def make_border_color_transparent(path: Path, color: tuple[int, int, int]) -> None:
    image = Image.open(path).convert("RGBA")
    width, height = image.size
    pixels = image.load()
    stack = []
    seen = set()

    for x in range(width):
        stack.append((x, 0))
        stack.append((x, height - 1))
    for y in range(height):
        stack.append((0, y))
        stack.append((width - 1, y))

    while stack:
        x, y = stack.pop()
        if (x, y) in seen or not (0 <= x < width and 0 <= y < height):
            continue
        seen.add((x, y))
        red, green, blue, alpha = pixels[x, y]
        if alpha == 0 or (red, green, blue) != color:
            continue
        pixels[x, y] = (0, 0, 0, 0)
        stack.extend(((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)))

    image.save(path)


def save_centered_transparent_sprite(source: Path, destination: Path, canvas_size: int = 96) -> None:
    image = Image.open(source).convert("RGBA")
    pixels = []
    for red, green, blue, alpha in image.getdata():
        if (red, green, blue) == (255, 255, 255):
            pixels.append((0, 0, 0, 0))
        else:
            pixels.append((red, green, blue, alpha))
    image.putdata(pixels)

    bbox = image.getbbox()
    if bbox:
        image = image.crop(bbox)

    canvas = Image.new("RGBA", (canvas_size, canvas_size), (0, 0, 0, 0))
    x = (canvas_size - image.width) // 2
    y = (canvas_size - image.height) // 2
    canvas.paste(image, (x, y), image)
    destination.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(destination)


def source_stem_candidates(name: str) -> list[str]:
    normalized = name.lower()
    candidates = [
        normalized,
        normalized.replace("_", ""),
        normalized.replace("_", "."),
        normalized.replace("_f", "f").replace("_m", "m"),
        normalized.replace("female", "f").replace("male", "m"),
    ]
    if normalized == "mr_mime":
        candidates.append("mr.mime")

    unique: list[str] = []
    for candidate in candidates:
        if candidate not in unique:
            unique.append(candidate)
    return unique


def first_existing_png(directory: Path, stems: list[str], suffix: str = "") -> Path | None:
    for stem in stems:
        candidate = directory / f"{stem}{suffix}.png"
        if candidate.exists():
            return candidate
    return None


def copy_pokemon_battle_sprites(
    extractor_root: Path, repo_root: Path, db_path: Path
) -> None:
    front_source = extractor_root / "pokemon-game-data/gfx/pokemon/front"
    back_source = extractor_root / "pokemon-game-data/gfx/pokemon/back"
    front_dest = repo_root / "public/assets/pokemon/front"
    back_dest = repo_root / "public/assets/pokemon/back"
    fetch_pokeapi = os.environ.get("CAPTUREQUEST_FETCH_POKEAPI_SPRITES", "1").lower()
    fetch_pokeapi = fetch_pokeapi not in {"0", "false", "no"}

    clean_dir(front_dest)
    clean_dir(back_dest)

    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute("SELECT id, name FROM pokemon ORDER BY id").fetchall()
    finally:
        conn.close()

    missing: list[str] = []
    pokeapi_copied = 0
    extractor_copied = 0
    copied = 0
    for pokemon_id, pokemon_name in rows:
        front_output = front_dest / f"{pokemon_id}.png"
        back_output = back_dest / f"{pokemon_id}.png"
        if fetch_pokeapi:
            if copy_pokeapi_battle_sprite(pokemon_id, "front", front_output):
                pokeapi_copied += 1
            else:
                missing.append(f"{pokemon_id}:{pokemon_name}:full-color-front")
        else:
            stems = source_stem_candidates(str(pokemon_name))
            front = first_existing_png(front_source, stems)
            if front is None:
                missing.append(f"{pokemon_id}:{pokemon_name}:front")
            else:
                save_centered_transparent_sprite(front, front_output)
                extractor_copied += 1

        if fetch_pokeapi:
            if copy_pokeapi_battle_sprite(pokemon_id, "back", back_output):
                pokeapi_copied += 1
            else:
                missing.append(f"{pokemon_id}:{pokemon_name}:full-color-back")
        else:
            stems = source_stem_candidates(str(pokemon_name))
            back = first_existing_png(back_source, stems, "b")
            if back is None:
                missing.append(f"{pokemon_id}:{pokemon_name}:back")
            else:
                save_centered_transparent_sprite(back, back_output)
                extractor_copied += 1

        if front_output.exists() and back_output.exists():
            copied += 2

    if missing:
        preview = ", ".join(missing[:8])
        raise RuntimeError(f"Missing Pokemon battle sprites: {preview}")

    print(
        f"Copied {copied} Pokemon battle sprites "
        f"({pokeapi_copied} from PokeAPI, {extractor_copied} from extractor fallback)."
    )


def copy_pokeapi_battle_sprite(pokemon_id: int, side: str, destination: Path) -> bool:
    if side == "front":
        url = f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/{pokemon_id}.png"
    elif side == "back":
        url = f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/{pokemon_id}.png"
    else:
        raise ValueError(f"unknown sprite side: {side}")

    data: bytes | None = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(url, timeout=15) as response:
                data = response.read()
            break
        except (urllib.error.URLError, TimeoutError):
            if attempt < 2:
                time.sleep(0.25 * (attempt + 1))
    if data is None:
        return False

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(data)
    return True


def copy_trainer_battle_sprites(extractor_root: Path, repo_root: Path) -> None:
    source = extractor_root / "pokemon-game-data/gfx/trainers"
    destination = repo_root / "public/assets/trainers"
    clean_dir(destination)

    copied = 0
    for source_file in sorted(source.glob("*.png")):
        trainer_dest = destination / source_file.name
        copy_file(source_file, trainer_dest)
        make_border_color_transparent(trainer_dest, (255, 255, 255))
        copied += 1

    copy_file(extractor_root / "pokemon-game-data/gfx/player/red.png", destination / "player_front.png")
    make_border_color_transparent(destination / "player_front.png", (255, 255, 255))
    copy_file(extractor_root / "pokemon-game-data/gfx/player/redb.png", destination / "player_back.png")
    make_border_color_transparent(destination / "player_back.png", (255, 255, 255))
    copied += 2
    print(f"Copied {copied} trainer battle sprites.")


def copy_phaser_assets(
    extractor_root: Path,
    repo_root: Path,
    db_path: Path,
    viewer_public: Path,
) -> None:
    phaser_root = repo_root / "public/phaser"

    copy_file(db_path, phaser_root / "pokemon.db")
    copy_file(viewer_public / "style.css", phaser_root / "style.css")

    clean_dir(phaser_root / "assets")
    copy_tree_contents(viewer_public / "assets", phaser_root / "assets")

    clean_dir(phaser_root / "tile_images")
    tile_count = copy_tree_contents(
        viewer_public / "viewer-assets/tile_images",
        phaser_root / "tile_images",
    )
    tile_catalog_sha256 = write_runtime_asset_contract(
        phaser_root,
        phaser_root / "pokemon.db",
    )
    write_runtime_asset_version(repo_root, tile_catalog_sha256)
    write_procedural_tile_palette(repo_root, phaser_root / "pokemon.db")

    sprite_dest = phaser_root / "sprites"
    clean_dir(sprite_dest, CAPTUREQUEST_ONLY_PHASER_SPRITES)
    sprite_count = copy_tree_contents(
        viewer_public / "viewer-assets/sprites",
        sprite_dest,
    )
    for sprite_file in sprite_dest.glob("*.png"):
        if sprite_file.name not in CAPTUREQUEST_ONLY_PHASER_SPRITES:
            make_color_transparent(sprite_file, (255, 255, 255))

    tileset_count = 0
    for source_file in sorted((extractor_root / "pokemon-game-data/gfx/tilesets").glob("*.png")):
        copy_file(source_file, sprite_dest / source_file.name)
        tileset_count += 1

    print(f"Copied {tile_count} tile images.")
    print(f"Copied {sprite_count} overworld sprites and {tileset_count} tilesets.")


def _validated_audio_artifacts(audio_root: Path) -> list[Path]:
    manifest_path = audio_root / "audio-render-manifest.json"
    if not manifest_path.is_file():
        return []
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    artifacts = manifest.get("artifacts")
    if not isinstance(artifacts, list) or len(artifacts) != 561:
        raise RuntimeError(
            f"Expected 561 rendered audio assets, found {len(artifacts) if isinstance(artifacts, list) else 'invalid manifest'}"
        )
    validated: list[Path] = []
    asset_keys: set[str] = set()
    logical_paths: set[str] = set()
    for artifact in artifacts:
        asset_key = artifact.get("assetKey")
        if not isinstance(asset_key, str) or not asset_key or asset_key in asset_keys:
            raise RuntimeError(f"Invalid or duplicate audio asset key: {asset_key!r}")
        asset_keys.add(asset_key)
        for representation in ("master", "distribution"):
            record = artifact.get(representation, {})
            logical_path = record.get("path")
            expected_hash = record.get("sha256")
            if not isinstance(logical_path, str) or not logical_path.startswith("/sound/pokemon/"):
                raise RuntimeError(f"Invalid audio path in render manifest: {logical_path!r}")
            if logical_path in logical_paths:
                raise RuntimeError(f"Duplicate audio path in render manifest: {logical_path!r}")
            logical_paths.add(logical_path)
            relative = Path(logical_path.removeprefix("/"))
            if relative.is_absolute() or ".." in relative.parts:
                raise RuntimeError(f"Unsafe audio path: {logical_path!r}")
            source = audio_root / relative
            if not source.is_file():
                raise RuntimeError(f"Missing rendered audio file: {source}")
            actual_hash = hashlib.sha256(source.read_bytes()).hexdigest()
            if actual_hash != expected_hash:
                raise RuntimeError(f"Rendered audio hash mismatch: {source}")
            validated.append(source)
    if len(asset_keys) != 561 or len(logical_paths) != 1122:
        raise RuntimeError("Audio manifest does not describe 561 distinct master/distribution pairs")
    return validated


def sync_audio_metadata(
    extractor_root: Path, repo_root: Path, audio_root: Path
) -> None:
    source_manifest = extractor_root / "audio_manifest.json"
    destination_manifest = repo_root / "src/constants/pokemon_audio_manifest.json"

    if source_manifest.exists():
        destination_manifest.parent.mkdir(parents=True, exist_ok=True)
        data = json.loads(source_manifest.read_text(encoding="utf-8"))
        destination_manifest.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print("Copied Pokemon audio manifest.")
    else:
        fallback_manifest = {
            "mapMusic": [],
            "music": {},
            "sfx": {},
            "pokemonCries": {},
        }
        destination_manifest.parent.mkdir(parents=True, exist_ok=True)
        destination_manifest.write_text(
            json.dumps(fallback_manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print("No extractor audio_manifest.json found; wrote empty Pokemon audio manifest.")

    validated_audio = _validated_audio_artifacts(audio_root)
    rendered_audio = audio_root / "sound/pokemon"
    destination_audio = repo_root / "public/sound/pokemon"
    if validated_audio:
        clean_dir(destination_audio)
        count = copy_tree_contents(rendered_audio, destination_audio)
        copy_file(
            audio_root / "audio-render-manifest.json",
            destination_audio / "audio-render-manifest.json",
        )
        print(f"Copied {count} rendered Pokemon audio files.")
    elif destination_audio.exists() and any(destination_audio.rglob("*.ogg")):
        print("Rendered Pokemon audio already exists in CaptureQuest public/sound/pokemon.")
    else:
        print("No rendered Pokemon audio found.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--extractor-root", type=Path, required=True)
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--database", type=Path, required=True)
    parser.add_argument("--viewer-public", type=Path)
    parser.add_argument("--audio-root", type=Path)
    args = parser.parse_args()

    extractor_root = args.extractor_root.resolve()
    repo_root = args.repo_root.resolve()
    database = args.database.resolve()
    viewer_public = (args.viewer_public or extractor_root / "pokemon-phaser/public").resolve()
    audio_root = (args.audio_root or extractor_root / "build/audio").resolve()

    copy_phaser_assets(extractor_root, repo_root, database, viewer_public)
    copy_pokemon_battle_sprites(extractor_root, repo_root, database)
    copy_trainer_battle_sprites(extractor_root, repo_root)
    sync_audio_metadata(extractor_root, repo_root, audio_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
